In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

C:\Users\User\AppData\Local\Temp\ipykernel_23968\998870465.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
#Importing the dataset
df = pd.read_csv("C:\\Users\\User\\Desktop\\Drive D\\New folder\\ML\\Completed\\AirBnb.csv")
df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-12-10,146.000000,165.000000,141.250000,144.710007,144.710007,70447500
1,2020-12-11,146.550003,151.500000,135.100006,139.250000,139.250000,26980800
2,2020-12-14,135.000000,135.300003,125.160004,130.000000,130.000000,16966100
3,2020-12-15,126.690002,127.599998,121.500000,124.800003,124.800003,10914400
4,2020-12-16,125.830002,142.000000,124.910004,137.990005,137.990005,20409600
5,2020-12-17,143.000000,152.449997,142.669998,147.050003,147.050003,15054700
6,2020-12-18,150.449997,159.000000,150.300003,157.300003,157.300003,15954200
7,2020-12-21,155.309998,172.000000,145.110001,163.020004,163.020004,17788100
8,2020-12-22,170.000000,174.970001,161.050003,163.190002,163.190002,9872600
9,2020-12-23,162.813995,168.250000,155.500000,158.009995,158.009995,5852500

In [3]:
df.set_index("Date",inplace=True)
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-12-10,146.000000,165.000000,141.250000,144.710007,144.710007,70447500
2020-12-11,146.550003,151.500000,135.100006,139.250000,139.250000,26980800
2020-12-14,135.000000,135.300003,125.160004,130.000000,130.000000,16966100
2020-12-15,126.690002,127.599998,121.500000,124.800003,124.800003,10914400
2020-12-16,125.830002,142.000000,124.910004,137.990005,137.990005,20409600
...,...,...,...,...,...,...
2024-01-08,137.309998,140.250000,136.610001,140.080002,140.080002,4179700
2024-01-09,138.520004,139.539993,137.789993,139.529999,139.529999,3560900
2024-01-10,139.199997,140.824997,138.699997,139.759995,139.759995,2492700
2024-01-11,140.710007,141.199997,137.550003,139.449997,139.449997,2383500
2024-01-12,139.350006,140.990005,137.130005,137.139999,137.139999,2480600

In [4]:
x = df.drop(columns=["Adj Close","Volume"])
x

                  Open        High         Low       Close
Date
2020-12-10  146.000000  165.000000  141.250000  144.710007
2020-12-11  146.550003  151.500000  135.100006  139.250000
2020-12-14  135.000000  135.300003  125.160004  130.000000
2020-12-15  126.690002  127.599998  121.500000  124.800003
2020-12-16  125.830002  142.000000  124.910004  137.990005
...                ...         ...         ...         ...
2024-01-08  137.309998  140.250000  136.610001  140.080002
2024-01-09  138.520004  139.539993  137.789993  139.529999
2024-01-10  139.199997  140.824997  138.699997  139.759995
2024-01-11  140.710007  141.199997  137.550003  139.449997
2024-01-12  139.350006  140.990005  137.130005  137.139999

[777 rows x 4 columns]

In [5]:
y = df['Adj Close']
y

Date
2020-12-10    144.710007
2020-12-11    139.250000
2020-12-14    130.000000
2020-12-15    124.800003
2020-12-16    137.990005
                 ...
2024-01-08    140.080002
2024-01-09    139.529999
2024-01-10    139.759995
2024-01-11    139.449997
2024-01-12    137.139999
Name: Adj Close, Length: 777, dtype: float64

In [6]:
#Splitting the dataset into training and testing
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

In [7]:
kernel_ridge_model = KernelRidge()

In [8]:
kernel_ridge_model.fit(x_train,y_train)

KernelRidge()

In [9]:
pred = kernel_ridge_model.predict(x_test)

In [10]:
r2_score(y_test,pred)

0.9999999993755213

In [11]:
mean_squared_error(y_test, pred)

5.932530962828509e-07